### ISSUE TITLE
Deprecation of `edm::RefToBase`

### ISSUE THREAD

**Issue by makortel** [cms-sw/framework-team#1124]
See https://github.com/cms-sw/cmssw/issues/42737

#### Old plan (kept for historical reference only)
- [x] #667
- [ ] Mark edm::RefToBase as CMS_DEPRECATED
- [x] #674
- [ ] Remove unused definitions of edm::RefToBase<T>
- [ ] Remove unused class template instantiations
- [ ] Make 3 class templates to produce PtrVector in addition of RefToBaseVector
- [ ] Migrate edm::RefToBase<reco::CaloCluster> to edm::Ptr
- [ ] Migrate edm::RefToBase<reco::Muon> to edm::Ptr
- [ ] Migrate edm::RefToBase<reco::Track> to edm::Ptr
- [ ] Migrate edm::RefToBase<reco::Jet> to edm::Ptr
- [ ] Migrate edm::RefToBase<reco::Candidate> to edm::Ptr
- [ ] Migrate edm::RefToBase<TrajectorySeed> to edm::Ptr
- [ ] Remove production of RefToBaseVector from 4 class templates 
- [ ] Remove the uses of RefToBase of reco::Photon, reco::Electron, and reco::GsfElectron
