### ISSUE TITLE
Improve Alpaka EDModule/ESModule API

### ISSUE THREAD

**Issue by makortel** [cms-sw/framework-team#1127]
This umbrella issue collects various activities done in the "Alpaka framework" after https://github.com/cms-sw/framework-team/issues/316 / https://github.com/cms-sw/framework-team/milestone/19 and https://github.com/cms-sw/framework-team/issues/696

- [ ] https://github.com/cms-sw/framework-team/issues/614
- [ ] https://github.com/cms-sw/framework-team/issues/635
- [ ] https://github.com/cms-sw/framework-team/issues/651
- [ ] https://github.com/cms-sw/framework-team/issues/698
- [ ] https://github.com/cms-sw/framework-team/issues/719
- [ ] https://github.com/cms-sw/framework-team/issues/727
- [ ] https://github.com/cms-sw/framework-team/issues/786
- [ ] https://github.com/cms-sw/framework-team/issues/824
- [ ] https://github.com/cms-sw/framework-team/issues/884
- [ ] https://github.com/cms-sw/framework-team/issues/902
- [ ] https://github.com/cms-sw/framework-team/issues/965
- [ ] https://github.com/cms-sw/framework-team/issues/1088
- [ ] https://github.com/cms-sw/framework-team/issues/1115
- [ ] https://github.com/cms-sw/framework-team/issues/1116
- [ ] https://github.com/cms-sw/framework-team/issues/1126
