### ISSUE TITLE
Reduce framework’s reliance on ROOT reflection

### ISSUE THREAD

**Issue by makortel** [cms-sw/framework-team#13]
Progress being tracked in https://github.com/makortel/framework/milestone/13

Motivations include
* support `std::array` (see https://github.com/cms-sw/cmssw/issues/30493)
* ease C++ modules
* ease GPU data products
* less annoyance

- [x] https://github.com/makortel/framework/issues/202
- [x] https://github.com/makortel/framework/issues/204
- [x] https://github.com/makortel/framework/issues/417
- [x] https://github.com/makortel/framework/issues/421
- [x] https://github.com/makortel/framework/issues/415

To do
- [ ] Remind ourselves of the earlier information
  - See https://github.com/cms-sw/cmssw/pull/38924
- [ ] Craft a plan what to do
- [ ] Implement the plan (piece by piece if possible)

**Comment by makortel** [comment]
Could try to replace the use of `edm::TypeWithDict` in `edm::ProductDescription` with `edm::TypeID`.
